// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.6.1.0
//      SpecFlow Generator Version:1.6.0.0
//      Runtime Version:4.0.30319.431
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace Example.Barista
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.6.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Deliver an order")]
    public partial class DeliverAnOrderFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "DeliverOrder.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Deliver an order", "In order to keep my job\r\nAs a barista\r\nI want to give the drinks to the customers" +
                    "", GenerationTargetLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Deliver a prepared order")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void DeliverAPreparedOrder()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Deliver a prepared order", new string[] {
                        "domain"});
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
 testRunner.Given("the manager has set up the menu");
#line 9
 testRunner.And("the cashier has queued an order for a small latte, whole milk");
#line 10
 testRunner.And("I have begun preparing the order");
#line 11
 testRunner.And("I have prepared the order");
#line 12
 testRunner.When("I deliver the order");
#line 13
 testRunner.Then("the order is delivered");
#line 14
 testRunner.And("nothing else happens");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Deliver an in-progress order")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void DeliverAnIn_ProgressOrder()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Deliver an in-progress order", new string[] {
                        "domain"});
#line 17
this.ScenarioSetup(scenarioInfo);
#line 18
 testRunner.Given("the manager has set up the menu");
#line 19
 testRunner.And("the cashier has queued an order for a small latte, whole milk");
#line 20
 testRunner.And("I have begun preparing the order");
#line 21
 testRunner.When("I deliver the order");
#line 22
 testRunner.Then("the order is prepared");
#line 23
 testRunner.And("the order is delivered");
#line 24
 testRunner.And("nothing else happens");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Deliver a queued order")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void DeliverAQueuedOrder()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Deliver a queued order", new string[] {
                        "domain"});
#line 27
this.ScenarioSetup(scenarioInfo);
#line 28
 testRunner.Given("the manager has set up the menu");
#line 29
 testRunner.And("the cashier has queued an order for a small latte, whole milk");
#line 30
 testRunner.When("I deliver the order");
#line 31
 testRunner.Then("the order is being prepared");
#line 32
 testRunner.And("the order is prepared");
#line 33
 testRunner.And("the order is delivered");
#line 34
 testRunner.And("nothing else happens");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
